### ISSUE TITLE
项目代码缺失

### ISSUE THREAD

**Issue by chiweiw** [zeratulag/TLCalculatorWPF#1]
1.项目import了jx3pz,但是没提交
2.引用了D:\Program Files (x86)\Syncfusion\Essential Studio\WPF\20.4.0.38\precompiledassemblies下面的几个dll，
3.    这三个文件不存在<Compile Include="ViewModels\Debug\DebugWindowViewModel.cs" />
    <Compile Include="ViewModels\Debug\DebugWindowViewModelShared.cs" />
    <Compile Include="ViewModels\Debug\FightTimeSummaryViewModelShared.cs" />

**Comment by zeratulag** [comment]
1. 已上传（ https://github.com/zeratulag/JYCalculatorWPF/tree/main/JX3PZ ）
2. 本项目使用了syncfusion的WPF控件，请从 https://www.syncfusion.com/wpf-controls 下载安装，或从Nuget搜索下载
3. 可以邮件说明详情
